version: '3'
services:

  php:
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "1280:80"

  db:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - "1281:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chinese-translator

volumes:
  postgres:
